# Generated by Django 3.1.2 on 2020-11-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netto', '0002_auto_20191229_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='position',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
