# Generated by Django 3.1.2 on 2020-11-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netto', '0004_device_dev_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='dev_type',
            new_name='device_type',
        ),
        migrations.AddField(
            model_name='device',
            name='device_series',
            field=models.CharField(blank=True, choices=[('Cisco Industrial Ethernet 2000 Switches', 'Cisco Industrial Ethernet 2000 Switches'), ('Cisco Industrial Ethernet 3000 Switches', 'Cisco Industrial Ethernet 3000 Switches'), ('Cisco Industrial Ethernet 4000 Switches', 'Cisco Industrial Ethernet 4000 Switches'), ('Cisco Industrial Ethernet 5000 Switches', 'Cisco Industrial Ethernet 5000 Switches'), ('Cisco Switch Catalyst 4500', 'Cisco Switch Catalyst 4500'), ('Cisco Switch Catalyst 4900', 'Cisco Switch Catalyst 4900'), ('Cisco Switch Catalyst 6800', 'Cisco Switch Catalyst 6800'), ('Cisco Switch Catalyst 3560', 'Cisco Switch Catalyst 3560'), ('Cisco Switch Catalyst 3750', 'Cisco Switch Catalyst 3750'), ('Cisco Switch Catalyst 6500', 'Cisco Switch Catalyst 6500'), ('Cisco Router ISR 1900', 'Cisco Router ISR 1900'), ('Cisco Router ISR 2900', 'Cisco Router ISR 2900'), ('Cisco Router ISR 3900', 'Cisco Router ISR 3900'), ('Cisco Router ISR 4000', 'Cisco Router ISR 4000'), ('Cisco Router ISR 1100', 'Cisco Router ISR 1100'), ('Cisco Router ISR 800', 'Cisco Router ISR 800'), ('Cisco Router ISR 900', 'Cisco Router ISR 900'), ('Cisco Router ASR 900', 'Cisco Router ASR 900'), ('Cisco Router ASR 1000', 'Cisco Router ASR 1000'), ('Cisco Router ASR 5000', 'Cisco Router ASR 5000'), ('Cisco Router ASR 9000', 'Cisco Router ASR 9000'), ('Cisco 8000 Series Routers', 'Cisco 8000 Series Routers'), ('Cisco Router 10000 Series', 'Cisco Router 10000 Series'), ('Cisco Router 12000 Series', 'Cisco Router 12000 Series'), ('Cisco Router ISR 1800', 'Cisco Router ISR 1800'), ('Cisco Router ISR 2800', 'Cisco Router ISR 2800'), ('Cisco Router ISR 3800', 'Cisco Router ISR 3800'), ('Cisco Router 7200 Series', 'Cisco Router 7200 Series'), ('Cisco Router 7600 Series', 'Cisco Router 7600 Series')], max_length=255),
        ),
    ]
