# Generated by Django 3.1.2 on 2020-11-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netto', '0005_auto_20201102_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prmts', models.IntegerField(default=3)),
            ],
        ),
    ]
