# Generated by Django 3.1.2 on 2020-11-11 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netto', '0007_auto_20201102_2344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
