# Generated by Django 3.1.2 on 2020-11-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netto', '0008_delete_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='messages',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
