# Generated by Django 3.1.2 on 2020-11-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netto', '0009_auto_20201114_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='commanline',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='log',
            name='messages',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
