# Generated by Django 3.1.3 on 2020-11-29 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netto', '0012_log_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='device',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='netto.device'),
        ),
    ]
