# Generated by Django 3.1.3 on 2020-11-29 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netto', '0013_auto_20201129_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='device',
        ),
    ]
