# Generated by Django 3.1.3 on 2020-11-29 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netto', '0014_remove_log_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='device',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='netto.device'),
            preserve_default=False,
        ),
    ]
