# Generated by Django 3.1.3 on 2020-11-29 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netto', '0015_log_device'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='device',
            new_name='device_id',
        ),
    ]
